<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>mat</string>
	</array>
	<key>name</key>
	<string>MAT Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.mat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.[a-z\+\-\*\&gt;\&lt;\=\%_][a-z0-9\+\-\*\&gt;\&lt;\=\%_]*</string>
			<key>name</key>
			<string>keyword.control.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.mat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.mat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(\[)(macro)\s+([a-z\+\-\*\&gt;\&lt;\=\%_][a-z0-9\+\-\*\&gt;\&lt;\=\%_]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(\[)([a-z\+\-\*\&gt;\&lt;\=\%_][a-z0-9\+\-\*\&gt;\&lt;\=\%_]*)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>constant.language.mat</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.mat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)[^a-z](adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya)[^a-z]</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.mat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[a-z\+\-\*\&gt;\&lt;\=\%_][a-z0-9\+\-\*\&gt;\&lt;\=\%_]*?:</string>
			<key>name</key>
			<string>constant.other.mat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#?[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.mat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)#?\$[0-9a-f]+</string>
			<key>name</key>
			<string>constant.numeric.mat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>keyword.control.mat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mat</string>
	<key>uuid</key>
	<string>fea7d49f-c96f-49ed-802b-c8dfb7b8f710</string>
</dict>
</plist>
